title: Sistema BCI
description: Sistema de Boletim de Cadastro Imobiliário
baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - venv
  - __pycache__
  - *.pyc 